/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.worker;
import Domain.*;
import controler.ClientControllerProfessionalDegree;
import controler.ClientControllerWorker;
import form.customer.SearchCustomer;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;


/**
 *
 * @author s
 */
public class AddWS extends javax.swing.JFrame {

    /**
     * Creates new form AddProfessionalDegree
     */
    public AddWS() {
        initComponents();
        fillData();
        addListener();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtWorker = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        cmbWorker = new javax.swing.JComboBox<>();
        txtDegree = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmbDegree = new javax.swing.JComboBox<>();
        jButtonAdd = new javax.swing.JButton();
        lblCmb = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Add Professional degree");

        jLabel2.setText("Worker:");

        jLabel3.setText("Search:");

        cmbWorker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbWorker.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbWorkerItemStateChanged(evt);
            }
        });

        jLabel4.setText("Professional degree:");

        jLabel5.setText("Search:");

        cmbDegree.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbDegree.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbDegreeItemStateChanged(evt);
            }
        });

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        lblCmb.setForeground(new java.awt.Color(255, 0, 0));
        lblCmb.setText("Worker already has this professional degree");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(201, 201, 201)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(jButtonAdd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(109, 109, 109)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbWorker, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 110, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(cmbDegree, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(48, 48, 48))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblCmb, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(76, 76, 76))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbDegree, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(13, 13, 13)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblCmb)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButtonAdd)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbDegreeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbDegreeItemStateChanged

//        lblCmb.setVisible(!proveriCmb());
    }//GEN-LAST:event_cmbDegreeItemStateChanged

    private void cmbWorkerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbWorkerItemStateChanged
//        lblCmb.setVisible(!proveriCmb());
    }//GEN-LAST:event_cmbWorkerItemStateChanged

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
ProfessionalDegree pd = (ProfessionalDegree) cmbDegree.getSelectedItem();
Worker w = (Worker) cmbWorker.getSelectedItem();

if (pd == null || w == null) {
    JOptionPane.showMessageDialog(this, "Both worker and degree must be selected", "ERROR", JOptionPane.ERROR_MESSAGE);
    return;
}

List<WrkPD> listOfWrkpd = new ArrayList<>();
w.setWs(listOfWrkpd);
WrkPD ws = new WrkPD(w, pd, LocalDate.now());

try {
    w.getWs().add(ws);
    int isAffected = ClientControllerWorker.getInstance().addWS(w);
    if (isAffected != 0) {
        fillData();
        JOptionPane.showMessageDialog(this, "System saved professionalDegree", "System", JOptionPane.INFORMATION_MESSAGE);
    } else {
        JOptionPane.showMessageDialog(this, "System did not save professionalDegree", "Error", JOptionPane.ERROR_MESSAGE);
    }
} catch (Exception ex) {
    JOptionPane.showMessageDialog(this, "Sistem ne može da zapamti stručnu spremu", "Error", JOptionPane.ERROR_MESSAGE);
    Logger.getLogger(AddWS.class.getName()).log(Level.SEVERE, null, ex);
}

    }//GEN-LAST:event_jButtonAddActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbDegree;
    private javax.swing.JComboBox<String> cmbWorker;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblCmb;
    private javax.swing.JTextField txtDegree;
    private javax.swing.JTextField txtWorker;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        try {
            List<AbstractDomainObject> w = ClientControllerWorker.getInstance().getWorkers(null);
            System.out.println(w);
            cmbWorker.setModel(new DefaultComboBoxModel(w.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(SearchWorker.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            List<AbstractDomainObject> pd = ClientControllerProfessionalDegree.getInstance().getProfessionalDegree(null);
//            System.out.println(pd);
            cmbDegree.setModel(new DefaultComboBoxModel(pd.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(SearchWorker.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbDegree.setSelectedIndex(-1);
        cmbWorker.setSelectedIndex(-1);

    }

    private void addListener() {
        txtWorker.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                System.out.println("usao u insert");
                updateWorker();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateWorker();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            private void updateWorker() {
                try {
                    List<AbstractDomainObject> w = ClientControllerWorker.getInstance().getWorkers(txtWorker.getText());
                    cmbWorker.setModel(new DefaultComboBoxModel(w.toArray()));
                } catch (Exception ex) {
                    Logger.getLogger(SearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        txtDegree.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateDegree();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateDegree();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }

            private void updateDegree() {
                try {
                    List<AbstractDomainObject> pd = ClientControllerProfessionalDegree.getInstance().getProfessionalDegree(new ProfessionalDegree(0, txtDegree.getText(), null));
                    cmbDegree.setModel(new DefaultComboBoxModel(pd.toArray()));
                } catch (Exception ex) {
                    Logger.getLogger(SearchCustomer.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

    }
}
