/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.receipt;

import controler.*;
import controler.ClientControllerReceipt;
import form.customer.AddCustomer;
import java.time.LocalDate;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import Domain.*;
import java.util.Date;

import model.TableModel;

/**
 *
 * @author s
 */
public class AddReceipt extends javax.swing.JFrame {

    private int quantity;
    private Worker worker;
    private int rbr=0;
    private List<AbstractDomainObject> paintings = new ArrayList<>();
    private List<AbstractDomainObject> items = new ArrayList<>();

    public Customer customer;

    /**
     * Creates new form AddReceipt
     * @param w
     */
    public AddReceipt(Worker w) {
        worker = w;
        initComponents();
        fillData();
        addListener();
        ReceiptCreater();

        quantity = 1;
    }

    public AddReceipt() {
        initComponents();
        fillData();
        
        quantity = 1;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblWorker = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cmbCustomer = new javax.swing.JComboBox<>();
        btnNewC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtSerch = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPainting = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblItems = new javax.swing.JTable();
        btnPlus = new javax.swing.JButton();
        btnMinus = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButtonDone = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        lblPrice = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lblFinalPrice = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnRemove = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel1.setText("User:");

        lblWorker.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        lblWorker.setText("Andrej");

        jLabel2.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel2.setText("Customer:");

        cmbCustomer.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btnNewC.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        btnNewC.setText("New Customer");
        btnNewC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewCActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        jLabel3.setText("Search:");

        txtSerch.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtSerch.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentAdded(java.awt.event.ContainerEvent evt) {
                txtSerchComponentAdded(evt);
            }
        });
        txtSerch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSerchActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        jLabel4.setText("ITEMS");

        tblPainting.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblPainting);

        tblItems.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tblItems);

        btnPlus.setText("+");
        btnPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlusActionPerformed(evt);
            }
        });

        btnMinus.setText("-");
        btnMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMinusActionPerformed(evt);
            }
        });

        txtQuantity.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        txtQuantity.setText("1");

        jButton2.setFont(new java.awt.Font("Verdana", 3, 12)); // NOI18N
        jButton2.setText("Add");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButtonDone.setFont(new java.awt.Font("Verdana", 0, 14)); // NOI18N
        jButtonDone.setText("Done");
        jButtonDone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDoneActionPerformed(evt);
            }
        });

        jLabel5.setText("Total price:");

        lblPrice.setText("price");

        jLabel8.setText("Finale price:");

        lblFinalPrice.setText("final price");

        jLabel10.setText("_________________________________________________________");

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(71, 71, 71))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(112, 112, 112)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnNewC))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 562, Short.MAX_VALUE)
                        .addComponent(btnRemove))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnMinus)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(btnPlus)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(11, 11, 11))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(341, 341, 341)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButtonDone)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(44, 44, 44)
                                        .addComponent(lblPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(32, 32, 32)
                                        .addComponent(lblFinalPrice)
                                        .addGap(19, 19, 19)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(btnNewC))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(lblWorker))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtSerch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(176, 176, 176))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnPlus)
                                    .addComponent(btnMinus)
                                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(jButton2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                .addGap(10, 10, 10)))
                        .addComponent(btnRemove)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(lblPrice))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(lblFinalPrice))
                        .addGap(2, 2, 2)
                        .addComponent(jButtonDone)
                        .addGap(66, 66, 66))))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed

        if (tblPainting.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "You must select item", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
       Painting painting = (Painting) ((TableModel) (tblPainting.getModel())).get(tblPainting.getSelectedRow());

        ReceiptItem i = containsPainting(painting);
        if (i != null) {
            i.setQuantity(i.getQuantity() + quantity);
            updateTblItems();
            updateLbls();
            txtQuantity.setText("1");
            quantity = 1;
            return;
        }
        rbr++;
            int quantiti=Integer.parseInt(txtQuantity.getText());
        ReceiptItem ri=new ReceiptItem(0,rbr, quantity, painting.getPrice(),quantiti*painting.getPrice(), painting);
  items.add(ri);
        updateTblItems();

        txtQuantity.setText("1");
        quantity = 1;

    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlusActionPerformed
        quantity++;
        txtQuantity.setText(quantity + "");
    }//GEN-LAST:event_btnPlusActionPerformed

    private void btnMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMinusActionPerformed
        if (quantity > 1) {
            quantity--;
            txtQuantity.setText(quantity + "");
        }
    }//GEN-LAST:event_btnMinusActionPerformed

    private void jButtonDoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDoneActionPerformed
     if (cmbCustomer.getSelectedIndex() == -1) {
            JOptionPane.showMessageDialog(this, "You must select a customer", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        if (items.isEmpty()) {
            JOptionPane.showMessageDialog(this, "System can not save the receipt", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        LocalDate date = LocalDate.now();
        Customer selectedCustomer = (Customer) cmbCustomer.getSelectedItem();
        List<ReceiptItem> receiptItems = new ArrayList<>();
        for (AbstractDomainObject i : items) {
            receiptItems.add((ReceiptItem) i);
        }
        double totalAmount = 0;
        for (ReceiptItem item : receiptItems) {
            if (item.getPrice() < 0 || item.getQuantity() < 0 || item.getValue() < 0) {
                JOptionPane.showMessageDialog(this, "Price, quantity or value cannot be less than zero", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            totalAmount += item.getValue();
        }

        Receipt receipt = new Receipt(0, date, totalAmount, worker, selectedCustomer, receiptItems);

        try {
            ClientControllerReceipt.getInstance().addReceipt(receipt);
            JOptionPane.showMessageDialog(this, "Receipt has been saved", "Success", JOptionPane.INFORMATION_MESSAGE);
            dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonDoneActionPerformed

    private void txtSerchComponentAdded(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_txtSerchComponentAdded
    }//GEN-LAST:event_txtSerchComponentAdded

    private void txtSerchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSerchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSerchActionPerformed

    private void btnNewCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewCActionPerformed
        AddCustomer ad = new AddCustomer(this);
        ad.setVisible(true);
        ad.setLocationRelativeTo(null);
    }//GEN-LAST:event_btnNewCActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        int i = tblItems.getSelectedRow();
        if (i == -1) {
            JOptionPane.showMessageDialog(this, "You must select item", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        items.remove(i);
        updateTblItems();
    }//GEN-LAST:event_btnRemoveActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMinus;
    private javax.swing.JButton btnNewC;
    private javax.swing.JButton btnPlus;
    private javax.swing.JButton btnRemove;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButtonDone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lblFinalPrice;
    private javax.swing.JLabel lblPrice;
    private javax.swing.JLabel lblWorker;
    private javax.swing.JTable tblItems;
    private javax.swing.JTable tblPainting;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextField txtSerch;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        lblWorker.setText(worker.getFirstName()+ " " + worker.getLastName());
        
        fillCmb();

        try {

            paintings = ClientControllerPainting.getInstance().getPaintings();

        } catch (Exception ex) {
            Logger.getLogger(AddReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }

        tblPainting.setModel(new TableModel(paintings));

        tblItems.setModel(new TableModel(items));

    }

    private void updateTblItems() {
        tblItems.setModel(new TableModel(items));
        updateLbls();

    }

    private void updateLbls() {
               double totalPrice = 0;
        for (AbstractDomainObject i : items) {
            totalPrice += ((ReceiptItem) (i)).getPrice()* ((ReceiptItem) (i)).getQuantity();
        }

        lblPrice.setText(totalPrice + "");
    }

    private ReceiptItem containsPainting(Painting painting) {
        for (AbstractDomainObject j : items) {
            if (((ReceiptItem) j).getPainting().getPaintingId()== painting.getPaintingId()) {
                return (ReceiptItem) j;
            }
        }
        return null;
    }

    private void addListener() {
        txtSerch.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                try {
                    paintings = ClientControllerPainting.getInstance().getPaintings(txtSerch.getText());
                } catch (Exception ex) {
                    Logger.getLogger(AddReceipt.class.getName()).log(Level.SEVERE, null, ex);
                }

                tblPainting.setModel(new TableModel(paintings));
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                try {
                    paintings = ClientControllerPainting.getInstance().getPaintings(txtSerch.getText());
                } catch (Exception ex) {
                    Logger.getLogger(AddReceipt.class.getName()).log(Level.SEVERE, null, ex);
                }

                tblPainting.setModel(new TableModel(paintings));
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
           }
        });
    }

    public void setCmb(Customer customer1) {
           customer = customer1;
        fillCmb();
        cmbCustomer.setSelectedItem(customer);
    }

    private void fillCmb() {
        List<AbstractDomainObject> c = new ArrayList<>();
        try {
            c = ClientControllerCustomer.getInstance().getCustomers(null);
            System.out.println(c);
        } catch (Exception ex) {
            Logger.getLogger(AddReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbCustomer.setModel(new DefaultComboBoxModel(c.toArray()));
    }

    private void ReceiptCreater() {
        
    }
}
