/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.receipt;

import controler.ClientControllerCustomer;
import controler.ClientControllerPainting;
import controler.ClientControllerReceipt;
import controler.ClientControllerWorker;
import java.awt.Color;
import java.awt.Font;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import Domain.*;
import model.TableModel;

/**
 *
 * @author s
 */
public class SearchReceipt extends javax.swing.JFrame {

    private List<AbstractDomainObject> c = new ArrayList<>();
    private List<AbstractDomainObject> w = new ArrayList<>();
    private List<AbstractDomainObject> d = new ArrayList<>();
    private List<Receipt> receiptForCb=new ArrayList<>();
    private List<Receipt> ri=new ArrayList();
    private List<Integer> receiptId=new ArrayList<>();
    Receipt receiptForFilter;

    /**
     * Creates new form SearchReceipt
     */
    public SearchReceipt() {
        initComponents();
        fillData();
        addListeners();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        cmbCustomer = new javax.swing.JComboBox<>();
        cmbWorker = new javax.swing.JComboBox<>();
        cmbPainting = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtWorker = new javax.swing.JTextField();
        txtCustomer = new javax.swing.JTextField();
        txtPainting = new javax.swing.JTextField();
        btnWorker = new javax.swing.JButton();
        btnCustomer = new javax.swing.JButton();
        btnPainting = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        lblNasao = new javax.swing.JLabel();
        txtReceipt = new javax.swing.JTextField();
        cmbReceipt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        btnReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        cmbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCustomer.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbCustomerItemStateChanged(evt);
            }
        });

        cmbWorker.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbWorker.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbWorkerItemStateChanged(evt);
            }
        });

        cmbPainting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPainting.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaintingItemStateChanged(evt);
            }
        });

        jLabel1.setText("Worker:");

        jLabel2.setText("Customer:");

        jLabel3.setText("Painting:");

        txtWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtWorkerActionPerformed(evt);
            }
        });

        txtCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCustomerActionPerformed(evt);
            }
        });

        btnWorker.setText("X");
        btnWorker.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnWorkerActionPerformed(evt);
            }
        });

        btnCustomer.setText("X");
        btnCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCustomerActionPerformed(evt);
            }
        });

        btnPainting.setText("X");
        btnPainting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPaintingActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        lblNasao.setText("jLabel4");

        cmbReceipt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbReceipt.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbReceiptItemStateChanged(evt);
            }
        });
        cmbReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbReceiptActionPerformed(evt);
            }
        });

        jLabel4.setText("ReceiptId:");

        btnReceipt.setText("X");
        btnReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(cmbWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtWorker, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnWorker))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jLabel1)))
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCustomer))
                    .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPainting, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(51, 51, 51)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtReceipt))
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPainting, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnPainting)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnReceipt)
                        .addContainerGap(12, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblNasao, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(145, 145, 145))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnEdit)
                                .addGap(18, 18, 18))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmbWorker, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnWorker)
                            .addComponent(cmbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnCustomer)
                            .addComponent(cmbPainting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnPainting)
                            .addComponent(cmbReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnReceipt)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtPainting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtReceipt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(35, 35, 35)))
                .addGap(7, 7, 7)
                .addComponent(lblNasao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmbWorkerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbWorkerItemStateChanged
        updateTable();
    }//GEN-LAST:event_cmbWorkerItemStateChanged

    private void cmbCustomerItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbCustomerItemStateChanged
        updateTable();
    }//GEN-LAST:event_cmbCustomerItemStateChanged

    private void cmbPaintingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaintingItemStateChanged
        updateTable();
    }//GEN-LAST:event_cmbPaintingItemStateChanged

    private void btnWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnWorkerActionPerformed

        cmbWorker.setSelectedIndex(-1);

    }//GEN-LAST:event_btnWorkerActionPerformed

    private void btnCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCustomerActionPerformed
        cmbCustomer.setSelectedIndex(-1);

    }//GEN-LAST:event_btnCustomerActionPerformed

    private void btnPaintingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPaintingActionPerformed

        cmbPainting.setSelectedIndex(-1);
    }//GEN-LAST:event_btnPaintingActionPerformed

    private void txtWorkerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtWorkerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtWorkerActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        try {                                        
            if (tbl.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "You have to select receipt first", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            Receipt r = (Receipt) ((TableModel) (tbl.getModel())).get(tbl.getSelectedRow());
            try {
                ri = ClientControllerReceipt.getInstance().getReceipts(r);
                if (!ri.isEmpty()) {
                    
                    JOptionPane.showMessageDialog(this, "The system has found the receipt", "System", JOptionPane.INFORMATION_MESSAGE);
                    r = (Receipt) ri.get(0);
                } else {
                    JOptionPane.showMessageDialog(this, "The system cannot find the receipt", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
            } catch (Exception ex) {
                Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
                JOptionPane.showMessageDialog(this, "The system cannot find the receipt", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            
            UpdateReceipt ur = new UpdateReceipt(this, r);
            ur.setVisible(true);
            ur.setLocationRelativeTo(null);
        } catch (Exception ex) {
               Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
           }
    }//GEN-LAST:event_btnEditActionPerformed

    private void txtCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCustomerActionPerformed

    private void cmbReceiptItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbReceiptItemStateChanged
        updateTable();
    }//GEN-LAST:event_cmbReceiptItemStateChanged

    private void btnReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReceiptActionPerformed
        cmbReceipt.setSelectedIndex(-1);
    }//GEN-LAST:event_btnReceiptActionPerformed

    private void cmbReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbReceiptActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbReceiptActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCustomer;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnPainting;
    private javax.swing.JButton btnReceipt;
    private javax.swing.JButton btnWorker;
    private javax.swing.JComboBox<String> cmbCustomer;
    private javax.swing.JComboBox<String> cmbPainting;
    private javax.swing.JComboBox<String> cmbReceipt;
    private javax.swing.JComboBox<String> cmbWorker;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNasao;
    private javax.swing.JTable tbl;
    private javax.swing.JTextField txtCustomer;
    private javax.swing.JTextField txtPainting;
    private javax.swing.JTextField txtReceipt;
    private javax.swing.JTextField txtWorker;
    // End of variables declaration//GEN-END:variables

    public void fillData() {

        try {
            c = ClientControllerCustomer.getInstance().getCustomers(null);
        } catch (Exception ex) {
            Logger.getLogger(AddReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbCustomer.setModel(new DefaultComboBoxModel(c.toArray()));

        try {
            w = ClientControllerWorker.getInstance().getWorkers(null);
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbWorker.setModel(new DefaultComboBoxModel(w.toArray()));

        try {
            d = ClientControllerPainting.getInstance().getPaintings();
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbPainting.setModel(new DefaultComboBoxModel(d.toArray()));
        try {
            receiptForCb = ClientControllerReceipt.getInstance().getReceipts(null);
            for(Receipt rece: receiptForCb){
                receiptId.add(rece.getReceiptId());
            }
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbReceipt.setModel(new DefaultComboBoxModel(receiptId.toArray()));
        cmbReceipt.setSelectedIndex(-1);
        cmbCustomer.setSelectedIndex(-1);
        cmbWorker.setSelectedIndex(-1);
        cmbPainting.setSelectedIndex(-1);

        try {
            ri = ClientControllerReceipt.getInstance().getReceipts(null);
            tbl.setModel(new TableModel(ri));
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void updateTable() {
        Worker w = null;
        Customer c = null;
        Painting d = null;
        int ReceiptID=0;
        if (cmbWorker.getSelectedIndex() != -1) {
            w = (Worker) cmbWorker.getSelectedItem();
        }
        if (cmbCustomer.getSelectedIndex() != -1) {
            c = (Customer) cmbCustomer.getSelectedItem();
        }
        if (cmbPainting.getSelectedIndex() != -1) {
            d = (Painting) cmbPainting.getSelectedItem();
        }
        if (cmbReceipt.getSelectedIndex() != -1) {
            ReceiptID = (int) cmbReceipt.getSelectedItem();
        }

        ReceiptItem receiptItem = new ReceiptItem(0, 0, 0, 0.0, 0.0,d);
        List<ReceiptItem> list = new ArrayList<>();
        list.add(receiptItem);

        Receipt receipt = new Receipt(ReceiptID, null, 0.0, w, c, list);

        try {
            ri= ClientControllerReceipt.getInstance().getReceipts(receipt);
            if(d!=null){
            List<Receipt> forShowing=new ArrayList<>();
            for(int i=0;i<ri.size();i++){
                for(int j=0;j<ri.get(i).getItemList().size();j++){
                    if(ri.get(i).getItemList().get(j).getPainting().getPaintingId()==(d.getPaintingId())){
                        forShowing.add(ri.get(i));
                        break;
                    }
                }
                lblupdate(!forShowing.isEmpty());
            tbl.setModel(new TableModel(forShowing));
            }
            }else{
            lblupdate(!ri.isEmpty());
            tbl.setModel(new TableModel(ri));
            }
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    public void updateWorker() {
        try {
            w = ClientControllerWorker.getInstance().getWorkers(txtWorker.getText());
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbWorker.setModel(new DefaultComboBoxModel(w.toArray()));
        cmbWorker.setSelectedIndex(-1);
    }

    public void updatePainting() {
        try {
            List<AbstractDomainObject> paintings = ClientControllerPainting.getInstance().getPaintings(txtPainting.getText());
            cmbPainting.setModel(new DefaultComboBoxModel(paintings.toArray()));
            cmbPainting.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }
  public void updateReceipt() throws Exception {
       String tekst = txtReceipt.getText();
       if(tekst.isEmpty()){receiptForCb = ClientControllerReceipt.getInstance().getReceipts(null);
       receiptId.clear();
            for(Receipt rece: receiptForCb){
                System.out.println("Udje li ovdje");
                receiptId.add(rece.getReceiptId());
            }
                cmbReceipt.setModel(new DefaultComboBoxModel(receiptId.toArray()));
                cmbReceipt.setSelectedIndex(-1);
                return;
       }
try {
    int broj = Integer.parseInt(tekst);
    if(receiptId.contains(broj)){
        receiptId.clear();
        receiptId.add(broj);
        cmbReceipt.setModel(new DefaultComboBoxModel(receiptId.toArray()));
        cmbReceipt.setSelectedIndex(-1);
    }
    else{
        receiptId.clear();
    cmbReceipt.setModel(new DefaultComboBoxModel(receiptId.toArray()));
    }
    // Validan broj – možeš dalje da koristiš promenljivu `broj`
    System.out.println("Unet broj je: " + broj);
} catch (NumberFormatException e) {
    // Nije unet validan broj
    JOptionPane.showMessageDialog(null, "Molimo unesite validan ceo broj!");
    receiptId.clear();
    cmbReceipt.setModel(new DefaultComboBoxModel(receiptId.toArray()));
    cmbReceipt.setSelectedIndex(-1);
}

    }
    public void updateCustomer() {
        try {
            List<AbstractDomainObject> customers = ClientControllerCustomer.getInstance().getCustomers(txtCustomer.getText());
            cmbCustomer.setModel(new DefaultComboBoxModel(customers.toArray()));
            cmbCustomer.setSelectedIndex(-1);
        } catch (Exception ex) {
            Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    private void addListeners() {
        txtWorker.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateWorker();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateWorker();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
       txtReceipt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                try {
                    updateReceipt();
                } catch (Exception ex) {
                    Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                try {
                    updateReceipt();
                } catch (Exception ex) {
                    Logger.getLogger(SearchReceipt.class.getName()).log(Level.SEVERE, null, ex);
                }
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
        txtCustomer.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updateCustomer();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updateCustomer();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });

        txtPainting.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent e) {
                updatePainting();
            }

            @Override
            public void removeUpdate(DocumentEvent e) {
                updatePainting();
            }

            @Override
            public void changedUpdate(DocumentEvent e) {
                throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
            }
        });
    }
    private void lblupdate(boolean b) {
        if (b) {
            lblNasao.setText("The system has found receipts matching the given criteria");
            lblNasao.setFont(new Font("Arial", Font.BOLD, 14));
            lblNasao.setForeground(new Color(0, 128, 0));
        } else {
            lblNasao.setText("The system could not find any receipts matching the given criteria");
            lblNasao.setFont(new Font("Arial", Font.BOLD, 14));
            lblNasao.setForeground(new Color(128, 0, 30));
        }
    }

}
