/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.receipt;

import controler.ClientControllerReceipt;
//import form.receiptItem.AddEdit;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Domain.*;
import controler.ClientControllerCustomer;
import form.receiptitem.AddEdit;
import java.time.LocalDate;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import model.TableModel;

/**
 *
 * @author s
 */
public class UpdateReceipt extends javax.swing.JFrame {
    private List<AbstractDomainObject> allCustomers=new ArrayList<>();
    private SearchReceipt parent;
    private Receipt receipt;
    public ReceiptItem novi;
    private Customer current;

    /**
     * Creates new form JFrame
     */
    public UpdateReceipt() {
        initComponents();
    }

    UpdateReceipt(SearchReceipt aThis, Receipt r) throws Exception {
        initComponents();
        receipt = r;
        parent = aThis;
        allCustomers=ClientControllerCustomer.getInstance().getCustomers(null);
        current=findCustomer(allCustomers,r.getCustomer().getCustomerId());
        jTextFieldCustomer.setText(current+"");
        fillCmb(allCustomers);
        fillData();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonAdd = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonEdit = new javax.swing.JButton();
        jButtonDodaj = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldCustomer = new javax.swing.JTextField();
        cmbCustomers = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Receipt Items:");

        jButtonAdd.setText("Add");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonDelete.setText("Delete");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonEdit.setText("Edit");
        jButtonEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEditActionPerformed(evt);
            }
        });

        jButtonDodaj.setText("Done");
        jButtonDodaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDodajActionPerformed(evt);
            }
        });

        jLabel2.setText("Customer:");

        cmbCustomers.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCustomers.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCustomersActionPerformed(evt);
            }
        });

        jLabel3.setText("Change customer:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonEdit, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(jButtonDelete, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonAdd, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addComponent(cmbCustomers, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(12, 90, Short.MAX_VALUE)
                                .addComponent(jButtonDodaj)))
                        .addGap(10, 10, 10))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 214, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(cmbCustomers, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextFieldCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(45, 45, 45)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonAdd)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonDelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEdit)
                        .addGap(60, 60, 60)
                        .addComponent(jButtonDodaj)))
                .addGap(24, 24, 24))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed

        AddEdit ad = new AddEdit(this);
        ad.setVisible(true);
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jButtonEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEditActionPerformed
        if (tbl.getSelectedRow() == -1) {
            JOptionPane.showMessageDialog(this, "Please select row", "ERROR", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ReceiptItem ri = (ReceiptItem) ((TableModel) tbl.getModel()).get(tbl.getSelectedRow());
        AddEdit ad = new AddEdit(this, ri);
        ad.setVisible(true);
        if(ad.isVisible()==true){
            JOptionPane.showMessageDialog(this, "System found the receipt", "ERROR", JOptionPane.INFORMATION_MESSAGE);
        }
        else{
            JOptionPane.showMessageDialog(this, "System can not find the receipt", "ERROR", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jButtonEditActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        try {
            if (tbl.getSelectedRow() == -1) {
                JOptionPane.showMessageDialog(this, "Please select row", "ERROR", JOptionPane.ERROR_MESSAGE);
                return;
            }
            ReceiptItem stari = (ReceiptItem) ((TableModel) tbl.getModel()).get(tbl.getSelectedRow());
//            int affectedRow=ClientControllerReceipt.getInstance().removeReceiptItem(stari);
            receipt.getItemList().remove(stari);
            fillData();
        } catch (Exception ex) {
            Logger.getLogger(UpdateReceipt.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonDodajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDodajActionPerformed
       
        try {
            double totalAmount=0;
            for(ReceiptItem ritem: receipt.getItemList()){
                totalAmount+=ritem.getValue();
            }
            receipt.setTotalAmount(totalAmount);
            receipt.setDate(LocalDate.now());
            receipt.setCustomer((Customer) cmbCustomers.getSelectedItem());
            boolean b = ClientControllerReceipt.getInstance().update(receipt);
            parent.fillData();
            JOptionPane.showMessageDialog(this, "System save the receipt", "Sistem", JOptionPane.INFORMATION_MESSAGE);

            dispose();
        } catch (Exception ex) {
            Logger.getLogger(UpdateReceipt.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "Sistem can not save the receipt", "ERROR", JOptionPane.ERROR_MESSAGE);

        }
    }//GEN-LAST:event_jButtonDodajActionPerformed

    private void cmbCustomersActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCustomersActionPerformed
        jTextFieldCustomer.setText(cmbCustomers.getSelectedItem()+"");
    }//GEN-LAST:event_cmbCustomersActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbCustomers;
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonDodaj;
    private javax.swing.JButton jButtonEdit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextFieldCustomer;
    private javax.swing.JTable tbl;
    // End of variables declaration//GEN-END:variables

    private void fillData() {
        tbl.setModel(new TableModel(receipt.getItemList()));

    }

        public void addItem(ReceiptItem i) {

        if (receipt.getItemList().contains(i)) {
            fillData();
            return;
        }
i.setReceiptId(receipt.getReceiptId());
i.setItemNumber(receipt.getItemList().size());
        receipt.getItemList().add(i);
        fillData();
    }

    public void updateReceiptItem(ReceiptItem ri) {
    ri.setReceiptId(receipt.getReceiptId());
    List<ReceiptItem> itemList = receipt.getItemList();
    for (int i = 0; i < itemList.size(); i++) {
        if (itemList.get(i).getItemNumber() == ri.getItemNumber()) {
            itemList.set(i, ri);  
            break;
        }
    }
        fillData();
    }
    public void AddReceiptItem(ReceiptItem ri){
         ri.setReceiptId(receipt.getReceiptId());
        ri.setItemNumber(receipt.getItemList().size());
        receipt.getItemList().add(ri);
        fillData();
    }

private Customer findCustomer(List<AbstractDomainObject> allCustomers, int customerId) {
    for (AbstractDomainObject obj : allCustomers) {
        Customer c = (Customer) obj; 
        if (c.getCustomerId() == customerId) {
            return c;
        }
    }
    return null; // a
}

    private void fillCmb(List<AbstractDomainObject> allCustomers) {
        cmbCustomers.setModel(new DefaultComboBoxModel(allCustomers.toArray()));
        cmbCustomers.setSelectedItem(current);
        
    }
}
