/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.customer;

import controler.ClientControllerCity;
import controler.ClientControllerCustomer;
import form.city.AddCity;
import form.receipt.AddReceipt;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import Domain.*;

/**
 *
 * @author s
 */
public class AddCustomer extends javax.swing.JFrame {

    public int mod = 0;
    private Customer customer;
    JFrame parent;

    /**
     * Creates new form AddCustomer
     */
    public AddCustomer() {
        initComponents();
        fillData();
        btnChange.setVisible(false);
    }


    public AddCustomer(SearchCustomer p) {
        mod = 1;
        initComponents();
        parent = p;
        fillData();
        btnChange.setVisible(false);
    }

    public AddCustomer(AddReceipt p) {
        mod = 3;
        initComponents();
        parent = p;
        fillData();
        btnChange.setVisible(false);
    }

    public AddCustomer(SearchCustomer p, Customer c) {
        initComponents();
        customer = c;
        parent = p;
        fillCustomer();
        fillData();
        btnAdd.setVisible(false);
        mod = 2;
        lblPoruka.setText("Customer has been found:");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtLastname = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        cmbCity = new javax.swing.JComboBox<>();
        btnAdd = new javax.swing.JButton();
        btnChange = new javax.swing.JButton();
        lblPoruka = new javax.swing.JLabel();
        jButtonAddCity = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("First name");

        jLabel2.setText("Last name");

        jLabel3.setText("Phone number");

        jLabel4.setText("City");

        cmbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCityActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnChange.setText(" Change");
        btnChange.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeActionPerformed(evt);
            }
        });

        lblPoruka.setText("Customer:");

        jButtonAddCity.setText("Add City");
        jButtonAddCity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddCityActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonAddCity)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 195, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(22, 22, 22)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(btnChange)
                                    .addGap(26, 26, 26)
                                    .addComponent(btnAdd))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbCity, 0, 219, Short.MAX_VALUE)
                                        .addComponent(txtPhone)
                                        .addComponent(txtLastname)
                                        .addComponent(txtName)))))))
                .addGap(80, 80, 80))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPoruka, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtLastname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cmbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButtonAddCity)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 70, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnChange))
                .addGap(42, 42, 42))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        String name = txtName.getText();
        String lastname = txtLastname.getText();
        String phone = txtPhone.getText();
        City city = (City) cmbCity.getSelectedItem();
       if (!phone.matches("\\d+")) {  // \d znači cifra, + znači jedan ili više puta
    JOptionPane.showMessageDialog(rootPane, "Phone number must contain only digits", "System", JOptionPane.ERROR_MESSAGE);
    return;
}
        if (name == null || !name.matches("[a-zA-Z]+") || lastname == null || !lastname.matches("[a-zA-Z]+") || name.isEmpty() || lastname.isEmpty() || phone == null || phone.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "The system cannot save the customer", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        if (city == null) {
    JOptionPane.showMessageDialog(rootPane, "Please select a city", "System", JOptionPane.ERROR_MESSAGE);
    return;
}

//        Customer c = new Customer(name, lastname, phone, city);
Customer c=new Customer(0, name, lastname, phone, city);

        try {
            c.setCustomerId(ClientControllerCustomer.getInstance().addCustomer(c));
            JOptionPane.showMessageDialog(this, "System saved the customer", "", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage(), "ERROR", JOptionPane.ERROR_MESSAGE);
        }

        if (mod == 1 || mod == 2) {
            ((SearchCustomer) parent).fillData();
        }
        if (mod == 3) {
            ((AddReceipt) parent).setCmb(customer);
        }
        dispose();

    }//GEN-LAST:event_btnAddActionPerformed

    private void btnChangeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeActionPerformed

        String name = txtName.getText();
        String lastname = txtLastname.getText();
        String phone = txtPhone.getText();
        City city = (City) cmbCity.getSelectedItem();

        if (name == null || !name.matches("[a-zA-Z]+") || lastname == null || !lastname.matches("[a-zA-Z]+") || name.isEmpty() || lastname.isEmpty() || phone == null || phone.isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "System has saved the customer", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        customer.setFirstName(txtName.getText());
        customer.setLastName(txtLastname.getText());
        customer.setPhoneNumber(txtPhone.getText());

        customer.setCity((City) cmbCity.getSelectedItem());

        try {
            ClientControllerCustomer.getInstance().updateCustomer(customer);
            JOptionPane.showMessageDialog(this, "System has saved the customer", "Done", JOptionPane.INFORMATION_MESSAGE);
        } catch (Exception ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(rootPane, "System did not save the customer", "Error", JOptionPane.ERROR_MESSAGE);

        }
        ((SearchCustomer) parent).fillData();
        dispose();
    }//GEN-LAST:event_btnChangeActionPerformed

    private void jButtonAddCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddCityActionPerformed
        AddCity ac = new AddCity(this);
        ac.setLocationRelativeTo(null);
        ac.setVisible(true);
    }//GEN-LAST:event_jButtonAddCityActionPerformed

    private void cmbCityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCityActionPerformed
 
    }//GEN-LAST:event_cmbCityActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnChange;
    private javax.swing.JComboBox<String> cmbCity;
    private javax.swing.JButton jButtonAddCity;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblPoruka;
    private javax.swing.JTextField txtLastname;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPhone;
    // End of variables declaration//GEN-END:variables

    public void fillData() {
        try {
            List<AbstractDomainObject> c = ClientControllerCity.getInstance().getCities();
            cmbCity.setModel(new DefaultComboBoxModel(c.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(AddCustomer.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void fillCustomer() {
        txtName.setText(customer.getFirstName());
        txtLastname.setText(customer.getLastName());
        txtPhone.setText(customer.getPhoneNumber());
        cmbCity.setSelectedItem(customer.getCity());
    }

    public void setCmb(City city) {
        cmbCity.setSelectedItem(city);
    }
}
