/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package form.receiptitem;

import controler.ClientControllerPainting;
import form.receipt.UpdateReceipt;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import Domain.*;
import javax.swing.JOptionPane;

/**
 *
 * @author s
 */
public class AddEdit extends javax.swing.JFrame {

    private int quantity = 1;
    private double discount = 0;
    private ReceiptItem ri;
    private UpdateReceipt parent;
    

    /**
     * Creates new form AddEdit
     */
    public AddEdit(UpdateReceipt aThis) {
        initComponents();
        fillData();
        parent = aThis;
        btnEdit.setVisible(false);
        ri = new ReceiptItem();
        ri.setQuantity(quantity);
    }

    public AddEdit(UpdateReceipt aThis, ReceiptItem ri) {
        initComponents();
        fillData();
        parent = aThis;
        btnAdd.setVisible(false);  
        this.ri = ri;
        quantity=ri.getQuantity();
        txtQuantity.setText(ri.getQuantity()+"");
        cmbPainting.setSelectedItem(ri.getPainting());
        lblTotalPrice.setText(ri.getValue()+"");
        System.out.println(ri.getQuantity());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cmbPainting = new javax.swing.JComboBox<>();
        jButtonPlus = new javax.swing.JButton();
        jButtonMinus = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        cmbPainting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cmbPainting.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbPaintingItemStateChanged(evt);
            }
        });

        jButtonPlus.setText("+");
        jButtonPlus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPlusActionPerformed(evt);
            }
        });

        jButtonMinus.setText("-");
        jButtonMinus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMinusActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtQuantity.setText("1");

        jLabel1.setText("Total price:");

        lblTotalPrice.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButtonMinus)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jButtonPlus))
                        .addComponent(cmbPainting, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(lblTotalPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnEdit)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdd)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(cmbPainting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPlus)
                    .addComponent(jButtonMinus)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblTotalPrice))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPlusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPlusActionPerformed
        quantity++;
        txtQuantity.setText(quantity + "");
        updateReceiptItem();
    }//GEN-LAST:event_jButtonPlusActionPerformed

    private void jButtonMinusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMinusActionPerformed
        if (quantity == 1) {
            return;
        }
        quantity--;
        txtQuantity.setText(quantity + "");
        updateReceiptItem();

    }//GEN-LAST:event_jButtonMinusActionPerformed

    private void cmbPaintingItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbPaintingItemStateChanged
        discount = 0;
//        lblDiscount.setText("0%");
        txtQuantity.setText(quantity + "");
        updateReceiptItem();
    }//GEN-LAST:event_cmbPaintingItemStateChanged

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed

        if (cmbPainting.getSelectedIndex() == -1) {
            return;
        }
        Painting selectedPainting=(Painting) cmbPainting.getSelectedItem();
        ri.setPainting(selectedPainting);
        ri.setPrice(selectedPainting.getPrice());
        ri.setQuantity(quantity);
        System.out.println(quantity+"OVo je kolicina ona ne radi");
        ri.setValue(quantity*selectedPainting.getPrice());
         System.out.println(ri.getItemNumber()+"Ovo je id nove stavke koji bi trebalo da je 0");
        parent.AddReceiptItem(ri);
        dispose();
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        if(cmbPainting.getSelectedIndex()==-1){
            JOptionPane.showMessageDialog(this,"You have to choose painting first", "Error", JOptionPane.ERROR_MESSAGE);
        } 
        else{
        Painting selectedPainting=(Painting) cmbPainting.getSelectedItem();
        ri.setPainting(selectedPainting);
        ri.setPrice(selectedPainting.getPrice());
       ri.setQuantity(quantity);
        System.out.println(quantity+"OVo je kolicina ona ne radi");
        ri.setValue(quantity*selectedPainting.getPrice());
        System.out.println(ri.getItemNumber()+"ovo je id azurirane stavke koji bi trebalo da je isti kao i ranije");
         parent.updateReceiptItem(ri);
        dispose();
        }
    }//GEN-LAST:event_btnEditActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JComboBox<String> cmbPainting;
    private javax.swing.JButton jButtonMinus;
    private javax.swing.JButton jButtonPlus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void fillData() {

        List<AbstractDomainObject> d;
        try {
            d = ClientControllerPainting.getInstance().getPaintings();
            cmbPainting.setModel(new DefaultComboBoxModel(d.toArray()));
        } catch (Exception ex) {
            Logger.getLogger(AddEdit.class.getName()).log(Level.SEVERE, null, ex);
        }
        cmbPainting.setSelectedIndex(-1);

    }
//
    private void updateReceiptItem() {
        if (cmbPainting.getSelectedIndex() == -1) {
            return;
        }
        Painting painting = (Painting) cmbPainting.getSelectedItem();
        lblTotalPrice.setText(quantity*painting.getPrice()+"");
    }

}
